#!/usr/bin/env bash
# Build gandalf's viewer and install a global `gandalf` launcher on PATH.
# Re-run any time (e.g. after moving the checkout or upgrading node).
#
#   ./scripts/install.sh            # installs to ~/.local/bin
#   GANDALF_BIN_DIR=/usr/local/bin ./scripts/install.sh
set -euo pipefail

GANDALF_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BIN_DIR="${GANDALF_BIN_DIR:-$HOME/.local/bin}"

# Prefer a CONCRETE mise node install: the `node` shim resolves its version from the current
# directory and fails outside a mise project (which is exactly where the launcher gets used).
concrete_node_dir() {
  ls -d "$HOME"/.local/share/mise/installs/node/*/bin 2>/dev/null \
    | grep -E '/node/[0-9][^/]*/bin$' | sort -V | tail -1
}

NODE_DIR="$(concrete_node_dir)"
[ -n "$NODE_DIR" ] && export PATH="$NODE_DIR:$PATH"
command -v node >/dev/null 2>&1 || { echo "✗ node not found — install Node >=20 (or mise)"; exit 1; }
echo "› node: $(command -v node) ($(node -v))"

echo "› Building the viewer (npm run build:web)…"
( cd "$GANDALF_HOME" && npm run build:web >/dev/null 2>&1 )

mkdir -p "$BIN_DIR"
LAUNCHER="$BIN_DIR/gandalf"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# gandalf launcher — generated by $GANDALF_HOME/scripts/install.sh (re-run to regenerate).
GANDALF_HOME="$GANDALF_HOME"
# Prefer a concrete mise node install (shims resolve the version from CWD and fail outside a mise project).
__nd="\$(ls -d "\$HOME"/.local/share/mise/installs/node/*/bin 2>/dev/null | grep -E '/node/[0-9][^/]*/bin\$' | sort -V | tail -1)"
[ -n "\$__nd" ] && export PATH="\$__nd:\$PATH"
command -v node >/dev/null 2>&1 || { echo "gandalf: node not found on PATH" >&2; exit 1; }
exec "\$GANDALF_HOME/node_modules/.bin/tsx" "\$GANDALF_HOME/bin/gandalf.ts" "\$@"
EOF
chmod +x "$LAUNCHER"

echo "✓ Installed: $LAUNCHER  →  $GANDALF_HOME/bin/gandalf.ts"
case ":$PATH:" in
  *":$BIN_DIR:"*) echo "✓ $BIN_DIR is on PATH" ;;
  *) echo "ℹ $BIN_DIR not on this (non-interactive) shell's PATH — your interactive shell likely has it" ;;
esac
echo "  try:  gandalf list"
